### ISSUE TITLE
I have a question about the Train and Test method

### ISSUE THREAD

**Issue by so-hyeun** [brunneis/ilab-erisk-clef-2020#1]
Hi, I've read the paper and have questions about the Train and Test method

1. In the case of Train, is it the same as the method of fine-tuning the BERT model for text classification? In this case, is it correct to understand that only text and tags are used without considering the user?

2. In the case of the test, it was said that the predicted probability is averaged. 
I wonder if 1) Did you take the method of storing the predicted value of the previous post in a specific variable, 
or 2) put the previous posts together as a model input.

      For instance, the input of case 1) is {post 1} {post 2} {post 3} ,,, 
      and the input of case 2) is {post 1} {post 1, post 2} {post 1, post 2, post 3},,,, 
      Which of the two is correct?

Thank you

**Comment by brunneis** [comment]
Hi @so-hyeun,

1. For training it's the same case as for text classification. Tagged texts are used but without taking into account their authors.
2. For testing, the input case is 1) {post 1} {post 2} {post 3}... 

Cheers :-)
